### ISSUE TITLE
Update Tutorials section

### ISSUE THREAD

**Issue by lianov** [informaticsclub/informaticsclub.github.io#17]
Hi all,

Just an FYI -  I have just re-structured the U-BDS training website a bit which included the removal of the data wrangling example I previously had. Given that you reference this link in your webpage at <https://informaticsclub.github.io/resources/> ("Data Wrangling by Dr. Lara Ianov of U-BDS"), can you remove this particular part so it doesn't lead to a broken link?

In the future, I will expand the section from additional training opportunities (e.g.: our planned data analysis workshops), so feel free to reference that if you would like.

**Comment by sdhutchins** [comment]
Thanks for the update!!! Sorry for not catching this earlier.
