### ISSUE TITLE
Compile Data Science & BIoinformatics Resources

### ISSUE THREAD

**Issue by sdhutchins** [informaticsclub/informaticsclub.github.io#3]
Our [resources](https://informaticsclub.github.io/resources/) page could use some work to link more tutorials on topics - especially learning more about getting started (learning python, R, linux, etc.).

I hope this issue will be an excellent place to start listing those.

**Comment by samuelbharti** [comment]
Closing this issue due to no response. We'll update current resources periodically and please open or contact us directly to get resources added
