### ISSUE TITLE
Add transparent white logo

### ISSUE THREAD

**Issue by sdhutchins** [informaticsclub/informaticsclub.github.io#5]
Hey, @mlogan42! I attached the white logo here.

I'll also put it on sharepoint.

![InformaticsClubLogoTransparentWhite](https://github.com/informaticsclub/informaticsclub.github.io/assets/20976111/a7198dac-9597-469c-9a67-e7a3be860aba)

**Comment by mlogan42** [comment]
New white logo updated.
